# Generated by Django 3.1.2 on 2020-12-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='logo')),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
