# Generated by Django 4.0.1 on 2022-01-29 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_featured',
        ),
    ]
